### ISSUE TITLE
changing Keywords in (after)intializer doesn't seem to work (Wicked::FIRST_STEP)

### ISSUE THREAD

**Issue by nruth** [schneems/wicked#231]
I'm a bit lost with how to change the wicked_first url string to something prettier / more acceptable to our client.

https://github.com/schneems/wicked#keywords suggests an initializer file like this should work:

```
Someapp.application.configure do
  config.after_initialize do
    Wicked::FIRST_STEP = 'w-begin'.freeze
    Wicked::LAST_STEP = 'w-last'.freeze
    Wicked::FINISH_STEP  = 'w-finish'.freeze
  end
end
```

The file is loading, as I'm getting these warnings on restarting the rails server & seeing link urls change:

```
=> Booting Puma
=> Rails 4.2.7.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
config/initializers/wicked.rb:3: warning: already initialized constant Wicked::FIRST_STEP
/Users/nruth/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/wicked-1.3.1/lib/wicked.rb:7: warning: previous definition of FIRST_STEP was here
config/initializers/wicked.rb:4: warning: already initialized constant Wicked::LAST_STEP
/Users/nruth/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/wicked-1.3.1/lib/wicked.rb:8: warning: previous definition of LAST_STEP was here
config/initializers/wicked.rb:5: warning: already initialized constant Wicked::FINISH_STEP
/Users/nruth/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/wicked-1.3.1/lib/wicked.rb:6: warning: previous definition of FINISH_STEP was here

```

but when visiting `http://localhost:3000/registration/w-begin` I get this error

```
Wicked::Wizard::InvalidStepError in RegistrationController#show
The requested step did not match any steps defined for this controller.

wicked (1.3.1) lib/wicked/wizard.rb:60:in `setup_step_from'
wicked (1.3.1) lib/wicked/wizard.rb:77:in `setup_wizard'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:432:in `block in make_lambda'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:164:in `block in halting'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:504:in `block in call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:504:in `each'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:504:in `call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.7.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.7.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.7.1) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.7.1) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.7.1) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.7.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.7.1) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
exception_notification (4.1.2) lib/exception_notification/rack.rb:32:in `call'
flipper (0.10.2) lib/flipper/middleware/memoizer.rb:55:in `call'
warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
warden (1.2.6) lib/warden/manager.rb:34:in `catch'
warden (1.2.6) lib/warden/manager.rb:34:in `call'
rack (1.6.5) lib/rack/etag.rb:24:in `call'
rack (1.6.5) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.5) lib/rack/head.rb:13:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.5) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.5) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.7.1) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
activerecord (4.2.7.1) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
lograge (0.4.0) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
remote_ip_proxy_scrubber (0.1.1) lib/remote_ip_proxy_scrubber/filter_proxy_ips.rb:34:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.5) lib/rack/runtime.rb:18:in `call'
rack-rewrite (1.5.1) lib/rack/rewrite.rb:24:in `call'
activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.5) lib/rack/lock.rb:17:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
rack (1.6.5) lib/rack/deflater.rb:35:in `call'
rack-cors (0.4.1) lib/rack/cors.rb:81:in `call'
/Users/nruth/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/font_assets-457dcfddc431/lib/font_assets/middleware.rb:29:in `call'
rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
hirefire-resource (0.3.7) lib/hirefire/middleware.rb:29:in `call'
railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
railties (4.2.7.1) lib/rails/application.rb:165:in `call'
rack (1.6.5) lib/rack/content_length.rb:15:in `call'
puma (3.8.1) lib/puma/configuration.rb:224:in `call'
puma (3.8.1) lib/puma/server.rb:590:in `handle_request'
puma (3.8.1) lib/puma/server.rb:425:in `process_client'
puma (3.8.1) lib/puma/server.rb:289:in `block in run'
puma (3.8.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

```

## Preinitializer

If I do this instead

config/application.rb
```
require File.expand_path('../boot', __FILE__)

module Wicked
  FIRST_STEP = 'w-begin'
  LAST_STEP = 'w-last'
  FINISH_STEP  = 'w-finish'
end

require 'rails/all'
```

The urls are no longer customised and the order of the constant redefinition warnings swap:

```
/Users/nruth/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/wicked-1.3.1/lib/wicked.rb:6: warning: already initialized constant Wicked::FINISH_STEP
config/application.rb:7: warning: previous definition of FINISH_STEP was here
/Users/nruth/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/wicked-1.3.1/lib/wicked.rb:7: warning: already initialized constant Wicked::FIRST_STEP
config/application.rb:5: warning: previous definition of FIRST_STEP was here
/Users/nruth/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/wicked-1.3.1/lib/wicked.rb:8: warning: already initialized constant Wicked::LAST_STEP
config/application.rb:6: warning: previous definition of LAST_STEP was here
```

What was the idea / use-case behind making these hard-coded strings into constants, and could the docs explain how that rails app changed the values? 

Or could we add a way to configure/customise them when Wicked boots up alongside rails?

**Comment by schneems** [comment]
If you go to `http://localhost:3000/registration/` it should forward to the first step by default. 

https://github.com/schneems/wicked/blob/46c141f44e07e7769cff305e3a4db0496efaeb40/lib/wicked/wizard.rb#L35-L37

**Comment by nruth** [comment]
Thanks! I'll use that instead. 
Closing since I don't have a reason to change the constants now.
